[package]
name = "AIStudioDataPreparation"
version = "0.1.0"
edition = "2021"

[dependencies]
file-format = "0.26.0"
base64 = "0.22.1"
calamine = { version = "0.26.1", features = ["dates"] }
chrono = "0.4.39"
pdfium-render = "0.8.27"
clap = { version = "4.5.27", features = ["derive"] }